apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: node-app 
  janus-idp.io/tekton: node-app
  backstage.io/kubernetes-id: node-app
  backstage.io/kubernetes-namespace: rhtap-app-development 
  app.kubernetes.io/part-of: node-app
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  