apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: node-app
  janus-idp.io/tekton: node-app
  backstage.io/kubernetes-id: node-app
  backstage.io/kubernetes-namespace: rhtap-app-development 
  app.kubernetes.io/part-of: node-app
resources: 
- deployment.yaml
- route.yaml
- service.yaml
